excluded:
  - Pods
  - Carthage
included:
  - FluxxKitExample/
identifier_name:
  excluded:
    - e
    - id
    - r
# !
line_length: 142
# !!
cyclomatic_complexity:
  warning: 15
# !!!
function_body_length: 65
reporter: "xcode"
