osx_image: xcode8.3
language: swift
before_install:
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install
  - carthage bootstrap --platform ios
script:
  - ./Pods/SwiftLint/swiftlint
  - xcodebuild test -workspace FluxxKitExample.xcworkspace -scheme FluxxKitExample -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7 Plus" | xcpretty -c
